name: Capstone project CICD pipeline
on: 
 push:
jobs:
 capstoneproject:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout the code
    uses: actions/checkout@v4
  - name: Install Java and Maven
    uses: actions/setup-java@v4
    with:
     distribution: 'temurin'
     java-version: '11'
     cache: maven
  - name: Build the code
    run: mvn package --file pom.xml
  - name: Install docker
    uses: docker/setup-buildx-action@v3
  - name: Login to dockerhub
    uses: docker/login-action@v2
    with:
     username: ${{ secrets.DOCKERHUB_USERNAME }}
     password: ${{ secrets.DOCKERHUB_TOKEN }}
  - name: Build and Push the Image
    uses: docker/build-push-action@v4
    with:
     context: .
     push: true 
     tags: ${{ secrets.DOCKERHUB_USERNAME }}/capstoneimage:latest
  - name: Executing helm chart on Kubernetes Server Remotely
    uses: appleboy/ssh-action@v0.1.10
    with:
     host: 3.81.64.38
     username: root 
     password: root 
     port: 22 
     script: |
      git clone https://github.com/Sonal0409/Vodafone-DevOps-CapstoneProject.git
      cd Vodafone-DevOps-CapstoneProject
      helm list -A
      helm install mavenbuild-dev ./webapp
      helm list -A
      kubectl get all
